import 'package:flutter/material.dart';
import 'package:practiceapp/elementbox.dart';

class PeriodicTable extends StatelessWidget {
  const PeriodicTable({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        children: [
          Row(
            children: [
              ElementBox(symbol: "H"),
              Container(width: 925),
              ElementBox(symbol: "He"),
            ],
          ),
          Row(
            children: [
              ElementBox(symbol: "Li"),
              ElementBox(symbol: "Be"),
              Container(width: 600),
              ElementBox(symbol: "B"),
              ElementBox(symbol: "C"),
              ElementBox(symbol: "N"),
              ElementBox(symbol: "O"),
              ElementBox(symbol: "F"),
              ElementBox(symbol: "Ne"),
            ],
          ),
          Row(
            children: [
              ElementBox(symbol: "Na"),
              ElementBox(symbol: "Mg"),
              Container(width: 600),
              ElementBox(symbol: "Al"),
              ElementBox(symbol: "Si"),
              ElementBox(symbol: "P"),
              ElementBox(symbol: "S"),
              ElementBox(symbol: "Cl"),
              ElementBox(symbol: "Ar"),
            ],
          ),
          Row(
            children: [
              ElementBox(symbol: "K"),
              ElementBox(symbol: "Ca"),
              ElementBox(symbol: "Sc"),
              Container(width: 60),
              ElementBox(symbol: "Ti"),
              ElementBox(symbol: "V"),
              ElementBox(symbol: "Cr"),
              ElementBox(symbol: "Mn"),
              ElementBox(symbol: "Fe"),
              ElementBox(symbol: "Co"),
              ElementBox(symbol: "Ni"),
              ElementBox(symbol: "Cu"),
              ElementBox(symbol: "Zn"),
              ElementBox(symbol: "Ga"),
              ElementBox(symbol: "Ge"),
              ElementBox(symbol: "As"),
              ElementBox(symbol: "Se"),
              ElementBox(symbol: "Br"),
              ElementBox(symbol: "Kr"),
            ],
          ),
          Row(
            children: [
              ElementBox(symbol: "Rb"),
              ElementBox(symbol: "Sr"),
              ElementBox(symbol: "Y"),
              Container(width: 60),
              ElementBox(symbol: "Zr"),
              ElementBox(symbol: "Nb"),
              ElementBox(symbol: "Mo"),
              ElementBox(symbol: "Tc"),
              ElementBox(symbol: "Ru"),
              ElementBox(symbol: "Rh"),
              ElementBox(symbol: "Pd"),
              ElementBox(symbol: "Ag"),
              ElementBox(symbol: "Cd"),
              ElementBox(symbol: "In"),
              ElementBox(symbol: "Sn"),
              ElementBox(symbol: "Sb"),
              ElementBox(symbol: "Te"),
              ElementBox(symbol: "l"),
              ElementBox(symbol: "Xe"),
            ],
          ),
          Row(
            children: [
              ElementBox(symbol: "Cs"),
              ElementBox(symbol: "Ba"),
              ElementBox(symbol: "La"),
              Container(width: 60),
              ElementBox(symbol: "Hf"),
              ElementBox(symbol: "Ta"),
              ElementBox(symbol: "W"),
              ElementBox(symbol: "Re"),
              ElementBox(symbol: "Os"),
              ElementBox(symbol: "Ir"),
              ElementBox(symbol: "Pt"),
              ElementBox(symbol: "Au"),
              ElementBox(symbol: "Hg"),
              ElementBox(symbol: "Tl"),
              ElementBox(symbol: "Pb"),
              ElementBox(symbol: "Bi"),
              ElementBox(symbol: "Po"),
              ElementBox(symbol: "At"),
              ElementBox(symbol: "Rn"),
            ],
          ),
          Row(
            children: [
              ElementBox(symbol: "Fr"),
              ElementBox(symbol: "Ra"),
              ElementBox(symbol: "Ac"),
              Container(width: 60),
              ElementBox(symbol: "Rf"),
              ElementBox(symbol: "Db"),
              ElementBox(symbol: "Sg"),
              ElementBox(symbol: "Bh"),
              ElementBox(symbol: "Hs"),
              ElementBox(symbol: "Mt"),
              ElementBox(symbol: "Ds"),
              ElementBox(symbol: "Rg"),
              ElementBox(symbol: "Cn"),
              ElementBox(symbol: "Nh"),
              ElementBox(symbol: "Fl"),
              ElementBox(symbol: "Mc"),
              ElementBox(symbol: "Lv"),
              ElementBox(symbol: "Ts"),
              ElementBox(symbol: "Og"),
            ],
          ),
          Container(height: 50),
          Row(
            children: [
              Container(width: 222),
              ElementBox(symbol: "Ce"),
              ElementBox(symbol: "Pr"),
              ElementBox(symbol: "Nd"),
              ElementBox(symbol: "Pm"),
              ElementBox(symbol: "Sm"),
              ElementBox(symbol: "Eu"),
              ElementBox(symbol: "Gd"),
              ElementBox(symbol: "Tb"),
              ElementBox(symbol: "Dy"),
              ElementBox(symbol: "Ho"),
              ElementBox(symbol: "Er"),
              ElementBox(symbol: "Tm"),
              ElementBox(symbol: "Yb"),
              ElementBox(symbol: "Lu"),
            ],
          ),
          Row(
            children: [
              Container(width: 222),
              ElementBox(symbol: "Th"),
              ElementBox(symbol: "Pa"),
              ElementBox(symbol: "U"),
              ElementBox(symbol: "Np"),
              ElementBox(symbol: "Pu"),
              ElementBox(symbol: "Am"),
              ElementBox(symbol: "Cm"),
              ElementBox(symbol: "Bk"),
              ElementBox(symbol: "Cf"),
              ElementBox(symbol: "Es"),
              ElementBox(symbol: "Fm"),
              ElementBox(symbol: "Md"),
              ElementBox(symbol: "No"),
              ElementBox(symbol: "Lr"),
            ],
          ),
        ],
      ),
    );
  }
}
